name: MSBuild

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'

env:
  SOLUTION_FILE_PATH: CP_Main_10.sln

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

      - name: Build Release x64
        run: msbuild ${{ env.SOLUTION_FILE_PATH }} /p:Configuration=Release /p:Platform=x64

      - name: Stamp version on Ditto.exe

        run: .\DittoSetup\rcedit-x64 Release64\Ditto.exe --set-file-version 3.25.${{ github.run_number }}.0 --set-product-version 3.25.${{ github.run_number }}.0

      - name: Build portable ZIP
        run: DittoSetup\BuildPortableZIP.bat "DittoPortable_3_25_${{ github.run_number }}_0" bit64

      - name: Zip debug symbols
        run: |
          7z a DittoSetup\output\DittoDebug_3_25_${{ github.run_number }}_0.7z *.pdb -r
          7z a DittoSetup\output\DittoDebug_3_25_${{ github.run_number }}_0.7z *.map -r

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Ditto-3_25_${{ github.run_number }}_0-artifacts
          path: |
            Release64/**/*.exe
            Release64/**/*.dll
            Release64/**/*.pdb
            DittoSetup/output/**/*.exe
            DittoSetup/output/**/*.7z
            DittoSetup/output/**/*.zip
            DittoSetup/output/**/*.msi
